### ISSUE TITLE
Volatility incoming - Bollinger bands width

### ISSUE THREAD

**Issue by jptsantossilva** [jptsantossilva/BEC#13]
Alerts - Volatility incoming - Bollinger bands width < X value

**Comment by Vendetta35-ship** [comment]
Hello, can you provide a windows installation tutorial, especially the way to Schedule Python Scripts and the way to create a DNS ?
Many thanks !

**Comment by jptsantossilva** [comment]
Hello,

Currently, installation instructions and support for this program are only available for Linux environments. I’d recommend setting up the program on a Linux system, as this is where it’s been tested and optimized. If you have access to a Linux machine (whether a dedicated machine or on a virtual machine with a dual-boot setup), I’ll be glad to assist you with the installation steps and provide any guidance you need.

Thank you for your understanding, and let me know if you decide to proceed with a Linux setup!
