### ISSUE TITLE
Dashboard Error

### ISSUE THREAD

**Issue by tecnologiamvv** [jptsantossilva/BEC#16]
![image](https://github.com/jptsantossilva/BEC/assets/83409594/a1069ec1-7cbd-4fe1-8e2d-89b42cd94753)

What could be causing this error? When running, this message appears.

**Comment by jptsantossilva** [comment]
On first start it may take a few minutes, like 10min, to get Balance data from Binance. On the first start will get data from last 30 days.

**Comment by tecnologiamvv** [comment]
The error persists even after a while. Is there anything to be done?

**Comment by jptsantossilva** [comment]
I'm doing some improvements on the dashboard. Get todays latest version, open dashboard and if there is no balance chart data click refresh button.

**Comment by tecnologiamvv** [comment]
Excellent job. The panel worked fine. To activate the bot just keep the bot running? Can I only have a balance in BUSD?

**Comment by htnlabs** [comment]
Is the balance not updated after a new deposit? Even clicking refresh, the balance is not updated.

**Comment by jptsantossilva** [comment]
> Is the balance not updated after a new deposit? Even clicking refresh, the balance is not updated.

The balance is a daily close snapshot and not a real-time balance. Its to be used to check the portfolio balance and its performance, on a daily basis. You can see that the most recent date is always the day before today. Its like a Daily close Balance. Maybe I should rename it and add an additional Real time Balance.

**Comment by jptsantossilva** [comment]
> Excellent job. The panel worked fine. To activate the bot just keep the bot running? Can I only have a balance in BUSD?

you can have other balances. The bot will only use BUSD if that's the one selected on the Dashboard Settings.

**Comment by htnlabs** [comment]
> > Is the balance not updated after a new deposit? Even clicking refresh, the balance is not updated.
> 
> The balance is a daily close snapshot and not a real-time balance. Its to be used to check the portfolio balance and its performance, on a daily basis. You can see that the most recent date is always the day before today. Its like a Daily close Balance. Maybe I should rename it and add an additional Real time Balance.

Tks. Good job.

**Comment by htnlabs** [comment]
> 0 * * * * cd ~/Documents/bot_BUSD && python3 main.py 1h prod
> 0 */4 * * * cd ~/Documents/bot_BUSD && python3 main.py 4h prod
> 0 0 * * * cd ~/Documents/bot_BUSD && python3 main.py 1d prod
> 0 0 * * * cd ~/Documents/bot_BUSD && python3 symbol_by_market_phase.py 1d BUSD
> */15 * * * * cd ~/Documents/bot_BUSD && python3 super_rsi.py

Does schedule.py in cron already solve it?

**Comment by htnlabs** [comment]
Two days running on busd but no open orders, is it normal for the strategy?

**Comment by jptsantossilva** [comment]
> > 0 * * * * cd ~/Documents/bot_BUSD && python3 main.py 1h prod
> > 0 */4 * * * cd ~/Documents/bot_BUSD && python3 main.py 4h prod
> > 0 0 * * * cd ~/Documents/bot_BUSD && python3 main.py 1d prod
> > 0 0 * * * cd ~/Documents/bot_BUSD && python3 symbol_by_market_phase.py 1d BUSD
> > */15 * * * * cd ~/Documents/bot_BUSD && python3 super_rsi.py
> 
> Does schedule.py in cron already solve it?

Schedule needs more development and testing

**Comment by jptsantossilva** [comment]
> Two days running on busd but no open orders, is it normal for the strategy?

If the trend is not going on strategy favour it stays aside. If you want to check, go to Dashboard - Best Ema and get ema fast and ema slow from the top performers list and open the charts on tradingview. If any ema fast crossed above ema slow it will buy and sell if otherwise. Keep in mind that backtesting to find best emas in each pair can take a few hours on a fresh bot install.

**Comment by htnlabs** [comment]
> 

Excellent.

> > Two days running on busd but no open orders, is it normal for the strategy?
> 
> If the trend is not going on strategy favour it stays aside. If you want to check, go to Dashboard - Best Ema and get ema fast and ema slow from the top performers list and open the charts on tradingview. If any ema fast crossed above ema slow it will buy and sell if otherwise. Keep in mind that backtesting to find best emas in each pair can take a few hours on a fresh bot install.

Excellent
