### ISSUE TITLE
Signals Log Empty on Dashboard Despite Receiving Telegram Signals

### ISSUE THREAD

**Issue by bloodrain88** [jptsantossilva/BEC#17]
**Description:**
I've been receiving signals via Telegram as expected, but when I check the Signals Log on the Dashboard, it's empty. The signals that are being sent to Telegram are not being reflected in the Dashboard's Signals Log.

**Steps to Reproduce:**

Receive a signal in Telegram.
Open the Dashboard and navigate to the Signals Log.
Expected Behavior:
The signals that are received in Telegram should also appear in the Signals Log on the Dashboard.

**Actual Behavior:**
The Signals Log on the Dashboard is empty, even though signals are being received in Telegram.

<img width="367" alt="image" src="https://github.com/jptsantossilva/BEC/assets/73248225/fe997cc2-0aaf-4c07-873e-1c5bfd0bcf42">
<img width="454" alt="Screenshot 2023-07-08 alle 07 56 56" src="https://github.com/jptsantossilva/BEC/assets/73248225/12fac73f-f9d9-4798-aa52-30741d303572">

**Comment by jptsantossilva** [comment]
Hi,
Thanks for the question. The signals record log to be shown on dashboard are the same as you receive on telegram signals alerts. These are signals that do not automatically trigger buy and sell orders, they are just informative. For now I'm using it for a signal I call super-rsi. The super-rsi signal is triggered when all time-frames are below or above the defined level.
RSI(14) 1d / 4h / 1h / 30m / 15m <= 25
RSI(14) 1d / 4h / 1h / 30m / 15m >= 80
I found it very useful in detecting blow-off tops.

To avoid misunderstandings I'm adding a description.

Buy and sell order are represented on unrealized and realized dashboard tabs.
I'm also planning to add the bollinger bands width for the same type of alert.
