### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by htnlabs** [jptsantossilva/BEC#18]
![image](https://github.com/jptsantossilva/BEC/assets/39269497/376cb09a-392a-4154-9b88-a8faafba46e4)

After performing the last update I had the error above. What can it be? How to fix?

**Comment by jptsantossilva** [comment]
Easy! You just need to restart the computer.

**Comment by htnlabs** [comment]
![image](https://github.com/jptsantossilva/BEC/assets/39269497/d8148172-5e5e-484a-a328-e610f2141466)

After reboot
