### ISSUE TITLE
where do I have to fill in my API keys ?

### ISSUE THREAD

**Issue by 000KeyserSoze000** [jptsantossilva/BEC#19]
Hello, and congratulations, is it possible to use without a virtual environment, and where do I have to fill in my API keys??

**Comment by jptsantossilva** [comment]
Thanks.
VM is optional. The API keys are stored as environment variables. The installation instructions are availabe on the main page. [Link to Instructions ](https://docs.google.com/document/d/1ERtxjcdrznMWXragmBh5ZimIn6_PGn2sde0j_x4CktA/edit?usp=sharing)
