### ISSUE TITLE
How can I connect to the dashboard?

### ISSUE THREAD

**Issue by ulotoyebtaa** [jptsantossilva/BEC#20]
Hello,

I finally was able to get this to work after your last update. Thanks a lot for a wonderful project.

Please how can I connect to the dashboard? It's requesting for a username and password.

Hope to hear from you soon.

Regards

**Comment by jptsantossilva** [comment]
Hi,

Thanks ;)

If you are at the installed machine use localhost:8501 and default credentials are admin / admin.

**Comment by ulotoyebtaa** [comment]
Thanks a lot, i was able to login but the dashboard is showing this error
below:

[image: image.png]

[image: image.png]
[image: image.png]

Please advise.

Thanks & Regards

**Comment by jptsantossilva** [comment]
Images are missing. Add them again.
